name: build

on:
  push:
    branches:
      - main

jobs:
  R-CMD:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest, r: '3.6.1'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}      
      GITHUB_PAT: ${{ secrets.GH_PAT_RMAP}}

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT_RMAP }}
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.r }}
      - uses: r-lib/actions/setup-pandoc@master
      - uses: r-lib/actions/setup-tinytex@master  
      - name: Brew and macOS config
        if: runner.os == 'macOS'
        run: |
          brew install pkg-config \
            imagemagick@6 \
            gdal

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"), repos = "https://cloud.r-project.org")          
          remotes::install_github("JGCRI/jgcricolors")
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
