name: docs

on:
  push:
    branches:
      - main

jobs:
  pkgdown:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    
    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: ubuntu-latest, r: 'devel', cran: "https://demo.rstudiopm.com/all/__linux__/xenial/latest"}
    
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true      
      GITHUB_PAT: ${{ secrets.GH_PAT}}

    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v2-branch
        with:
          r-version: '3.6'
      - uses: r-lib/actions/setup-pandoc@v2-branch
      - uses: r-lib/actions/setup-tinytex@v2-branch
          
      - name: Ubuntu config
        if: startsWith(matrix.config.os, 'ubuntu')
        run: |
          sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libudunits2-dev libgdal-dev libgeos-dev libproj-dev libmagick++-dev libavfilter-dev
      
      - name: Install dependencies
        run: |
          install.packages(c("remotes","rcmdcheck"), repos = "https://cloud.r-project.org")
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Deploy package
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
          
      - name: Track file
        run: |
          git add .github/r-depends.rds
          git commit -m "track file"
      
      - name: Rename file
        run: |
          git mv csheet.pdf cheatsheet.pdf
      
      - name: Auto commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: gh-pages
          push_options: --force