name: docs

on:
  push:
    branches:
      - main

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true    
      GITHUB_PAT: ${{ secrets.GH_PAT}}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.0'

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libssl-dev libxml2-dev libudunits2-dev libgdal-dev libgeos-dev libproj-dev libmagick++-dev libavfilter-dev
      
      - name: Restart R
        run: |
          R --vanilla --quiet
          echo 'q()' | R --no-save

      - name: Install dependencies 1
        run: |
          install.packages(c("remotes", "rcmdcheck"), repos = "https://cloud.r-project.org")
        shell: Rscript {0}

      - name: Install dependencies 2
        run: |
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Install dependencies 3
        run: |
          install.packages("pkgdown")
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: Deploy package
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
          
      - name: Track file
        run: |
          git add .github/r-depends.rds
          git commit -m "track file"
      
      - name: Rename file
        run: |
          git mv csheet.pdf cheatsheet.pdf
      
      - name: Auto commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: gh-pages
          push_options: --force